// =============================================================================
// Graphene: Federation Type Definitions
// =============================================================================

// ---------------------------------------------------------------------------
// Envelope — every S2S payload is wrapped in this before being signed and sent.
// The signature covers the canonical JSON of `payload`, NOT the envelope itself,
// so receivers can verify content integrity independently of transport headers.
// ---------------------------------------------------------------------------

export type FederationActivityType = 'Create' | 'Update' | 'Delete' | 'Vote' | 'Announce';

export interface FederationEnvelope {
    /** Activity type — drives the handler branch in the inbox router. */
    type: FederationActivityType;

    /** Canonical domain of the instance that produced this envelope.
     *  Used by the receiver to fetch our public key via GET /federation/actor */
    actor_domain: string;

    /** ISO-8601 timestamp. Receivers MUST reject envelopes older than 5 min
     *  to mitigate replay attacks. */
    timestamp: string;

    /** The raw activity object (FederatedPost, FederatedVote, etc.) */
    payload: FederatedPost | FederatedVote | FederatedDelete | FederatedAnnounce;

    /** secp256k1 signature over canonical JSON of `payload`.
     *  Produced by the sending instance's INSTANCE_PRIVATE_KEY. */
    signature: string;
}

// ---------------------------------------------------------------------------
// Activity payloads
// ---------------------------------------------------------------------------

export interface FederatedPost {
    /** UUID generated by the origin instance. Globally unique. */
    id: string;
    author_did: string;
    title: string;
    content: string;
    subreddit?: string;
    media_url?: string;
    media_type?: 'image' | 'video';
    created_at: string;
    /** Origin instance domain, denormalised for quick queries. */
    source_instance_url: string;
}

export interface FederatedVote {
    post_id: string;
    voter_did: string;
    /** 1 = upvote, -1 = downvote, 0 = retract */
    vote_type: 1 | -1 | 0;
    source_instance_url: string;
}

export interface FederatedDelete {
    /** UUID of the post being deleted. */
    post_id: string;
    author_did: string;
    source_instance_url: string;
}

// ---------------------------------------------------------------------------
// Announce — sent by a peer to introduce themselves and optionally
// register a federated community they host.
// ---------------------------------------------------------------------------
export interface FederatedAnnounce {
    /** The bare domain of the announcing instance, e.g. "203.0.113.5" */
    instance_domain: string;
    /** Human-readable name of the instance. */
    instance_name?: string;
    /** Optional: community this instance wants to share with us. */
    community?: {
        name: string;
        description?: string;
        topic?: string;
    };
}

// ---------------------------------------------------------------------------
// Instance actor — returned by GET /federation/actor so peers can verify sigs.
// Inspired by ActivityPub's Actor but kept minimal for Graphene.
// ---------------------------------------------------------------------------

export interface InstanceActor {
    /** e.g. "https://api.my-server.com/federation/actor" */
    id: string;
    type: 'Application';
    /** Human-readable server name. */
    name: string;
    /** Ethereum address derived from INSTANCE_PRIVATE_KEY — the public identifier. */
    public_address: string;
    /** Inbox endpoint for receiving S2S envelopes. */
    inbox: string;
}

// ---------------------------------------------------------------------------
// Internal result types used by the inbox handler
// ---------------------------------------------------------------------------

export interface InboxProcessResult {
    accepted: boolean;
    reason?: string;
}
